### PR TITLE
Support multiple destinations

### PR DESCRIPTION
**Pull request by shwilliam**
Not quite finished with the implementation of multiple destination support as discussed in #1 but thought I would open this PR to discuss the component API and design decisions.

To do:
- [ ] Write tests
- [x] Fix `<nav>` ARIA-label to handle multiple instances of skip-link list
- [x] Validate shape of `to` prop

### CODE REVIEW

**Comment by ktquez** [comment]
Awesome @shwilliam 

I've been a little busy these last few days, but early next week I can help you with whatever you need.

**Comment by shwilliam** [comment]
Sweet! Would particularly like to get some feedback on the API for the proposed `vue-skip-to-list` component.

**Comment by ktquez** [comment]
Hello @shwilliam, how are you?

I found it amazing what you are doing, do you need any help finalizing the `vue-skip-to-list`?

Ahh, what do you think about using aria-label to describe links more?

**Comment by shwilliam** [comment]
Always happy to help! I will have some time during the coming days to fix some things, add some tests, ensure a11y labels are correct then would love a code review.

Overall, are you okay with the api as seen in the added [demo](https://github.com/shwilliam/vue-skip-to/blob/multiple-destinations/demo/skip-to-list.html)?

**Comment by shwilliam** [comment]
Please let me know what you think of the updates and if you have any problems running the initial test I added.

Regarding providing labels with `aria-label`, I think it would be a good idea to give this responsibility to the user allowing them to provide any label text they wish. Perhaps by passing this in the `to` prop like the following:

```html
<vue-skip-to-list
  :to="[
    {anchor: '#main', label: 'Main', 'aria-label': 'Skip to main'},
    {anchor: '#footer', label: 'Footer', 'aria-label': 'Skip to footer'},
  ]"
>
  Skip links
</vue-skip-to-list>
```

Another option would be to generate this label using the `label` text provided by the user.

**Comment by ktquez** [comment]
@shwilliam 

I agree with you, we can let the user customize the `aria-label`.

**Review by ktquez — APPROVED** [review]

**Comment by ktquez** [comment]
Hello @shwilliam, how are you?

I remembered the feature you were developing, how can I help you to approve and publish your feature?

**Comment by shwilliam** [comment]
Hey, Alan! Doing great just very busy at this time, you?

All that's really left is adding some tests for the multiple destinations api/functionality. I held off on doing so initially as the existing test for focus on the existing component is failing for me. Is this the case for you?

Happy to dig into why or find an alternative strategy for asserting that focus is moving as intended so that we can get this merged.

**Comment by ktquez** [comment]
Great.
I will take a look too.

**Comment by ktquez** [comment]
@shwilliam 

In the `next` branch, the tests are working.

I'm working on this branch to add new features and fixes. 
Could you rebase your branch with the "next" branch?

I sent a message for you in DM twitter

**Comment by shwilliam** [comment]
Development of this feature has moved to the [`next` branch](/vue-a11y/vue-skip-to/tree/next). See #11.

**Pull request closed without merging**
